---
releases:
  - name: hello-dev
    namespace: default
    labels:
      environment: dev
    chart: mychart
    values:
      - values.yaml
      - secrets.enc.yaml
    set:
      - name: image.repository
        value: nginxdemos/hello
      - name: image.tag
        value: latest
      - name: secret.value
        value: mysecretvalue-dev
  - name: hello-stage
    namespace: default
    labels:
      environment: stage
    chart: mychart
    values:
      - values.yaml
      - secrets.enc.yaml
    set:
      - name: image.repository
        value: nginxdemos/hello
      - name: image.tag
        value: latest
      - name: secret.value
        value: mysecretvalue-stage
